"Name: \PR:SAPMV45A\FO:CUA_SETZEN\SE:END\EI
ENHANCEMENT 0 ZEI_SALE_PROMOTION.
*
  IF MODUL-POOL = 'SAPMV45B'
  AND T185V-STATUS = 'U'.
*   Status setzen
    SET PF-STATUS T185V-STATUS EXCLUDING CUA_EXCLUDE
                               OF PROGRAM  'SAPLZFG_BM_SALE_PROMOTION'.
  ENDIF.

ENDENHANCEMENT.
