"Name: \PR:SAPMV45A\IC:MV45AFZZ\SE:END\EI
ENHANCEMENT 0 ZEI_SALE_PROMOTION.
*
FORM 9999_FCODE_ZZPROMO.

    CALL FUNCTION 'ZFM_SALE_PROMOTION_CHECK'
      EXPORTING
        IS_TVAK       = TVAK
        IS_VBAK       = VBAK
        IS_VBKD       = VBKD
      CHANGING
        CT_VBAP       = XVBAP[]
        CT_KOMV       = XKOMV[].
ENDFORM.
ENDENHANCEMENT.
